STY: Fix additional `nibabel` image loading type errors
Fix `nibabel` image loading type errors: use the internal `load_api`
function to coerce type checking to consider the loaded image as a
`Nifti1Image` instead of a `FileBasedImage`, which is not guaranteed to
have e.g. the `get_zooms` attribute.

Fixes:
```
test/test_registration.py:79: error:
 Argument 1 to "displacements_within_mask" has incompatible type "FileBasedImage";
 expected "SpatialImage"  [arg-type]
test/test_registration.py:80: error:
 "FileBasedHeader" has no attribute "get_zooms"  [attr-defined]
```

raised for example in:
https://github.com/nipreps/nifreeze/actions/runs/18428068089/job/52511890135?pr=273#step:8:52

Left behind in commit 78bcc61.