STY: Fix miscellaneous type check errors (part 3)
Fix miscellaneous type check errors:
- Assert that an axis figure attribute is a `Figure` instance rather
  than annotating its type. Fixes a type check error introduced in
  commit 3c9f597.
- Ensure that the `TEST_DATA_HOME` environment variable is not
  `None`before converting it to a `Path` instance.

Fixes:
```
test/test_motion_viz.py:67: error:
 Incompatible types in assignment (expression has type "Figure | SubFigure", variable has type "Figure")  [assignment]
test/test_motion_viz.py:156: error:
 Incompatible types in assignment (expression has type "Figure | SubFigure", variable has type "Figure")  [assignment]
```

and
```
test/test_main.py:71: error:
 Argument 1 to "Path" has incompatible type "str | None"; expected "str | PathLike[str]"  [arg-type]
```

raised for example in:
https://github.com/nipreps/nifreeze/actions/runs/18445645344/job/52551975423?pr=273#step:8:57
and
https://github.com/nipreps/nifreeze/actions/runs/18445645344/job/52551975423?pr=273#step:8:59