FIX: Disallow `None` values when initializaing PET data object
Disallow `None` values when initializaing PET data object: all
`frame_time`, `total_duration`, and `uptake` values are required to
build a `PET` data object. Thus, remove `None` from the type annotation
values.

Fixes:
```
typecheck: commands[0]> mypy .
src/nifreeze/estimator.py:269: error: Value of type "ndarray[Any, Any] | None" is not indexable  [index]
```

raised in:
https://github.com/nipreps/nifreeze/actions/runs/18052738286/job/51377557942?pr=203#step:8:34