STY: Fix GQI model type checking errors
Fix GQI model type checking errors:
- Remove non-existing parameter from `odf` call.
- Provide `width` as a keywrod argument rather than a positional
  argument.
- Use `None` instead of the non-existing `np.Null` when no data needs to
  be returned.

Fixes:
```
src/nifreeze/model/gqi.py:150: error:
 Too many arguments for "odf"  [call-arg]
```

and
```
src/nifreeze/model/gqi.py:308: error:
 Too many positional arguments for "equatorial_zone_vertices"  [misc]
src/nifreeze/model/gqi.py:362: error:
 Too many positional arguments for "equatorial_zone_vertices"  [misc]
```

and
```
src/nifreeze/model/gqi.py:337: error:
 Module has no attribute "Null"  [attr-defined]
src/nifreeze/model/gqi.py:354: error:
 Module has no attribute "Null"  [attr-defined]
```

raised for example at:
https://github.com/nipreps/nifreeze/actions/runs/18449395416/job/52560821339?pr=273#step:8:34