STY: Fix miscellaneous static check failures
Fix miscellaneous static check failures: transition to the more modern
`attrs` API in lieu of `attr`:
- Install the `attrbs` package and the missing type stubs for the
  `attrs` library.
- Adapt the corresponding properties: use `@attrs.define` instead of
  `@attr.s`, and `attrs.field` instead of `attr.ib`.
- Add missing annotations for `data.base.BaseDataset` and
 `data.dmri.DWI` attributes.

Fixes:
```
Cannot find implementation or library stub for module named "attr"
```

and
```
src/nifreeze/data/base.py:32: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
src/nifreeze/data/pet.py:30: error: Cannot find implementation or library stub for module named "attrs"  [import-not-found]
src/nifreeze/data/pet.py:170: error: Unexpected keyword argument "dataobj" for "PET"  [call-arg]
.tox/typecheck/lib/python3.12/site-packages/mypy/typeshed/stdlib/builtins.pyi:110: note: "PET" defined here
src/nifreeze/data/pet.py:170: error: Unexpected keyword argument "affine" for "PET"  [call-arg]
.tox/typecheck/lib/python3.12/site-packages/mypy/typeshed/stdlib/builtins.pyi:110: note: "PET" defined here
```

and
```
rc/nifreeze/data/base.py:86: error: Need type annotation for "_filepath"  [var-annotated]
src/nifreeze/data/dmri.py:73: error: Need type annotation for "bzero"  [var-annotated]
src/nifreeze/data/dmri.py:75: error: Need type annotation for "gradients"  [var-annotated]
```

and other similar errors raised for exmaple at:
https://github.com/nipreps/nifreeze/actions/runs/15162795559/job/42632741133#step:8:33
https://github.com/nipreps/nifreeze/actions/runs/15174700127/job/42672566195?pr=133#step:8:33

Documentation:
https://www.attrs.org/en/stable/index.html