ENH: Make `linear_iterator` return an iterator
Make `linear_iterator` return an iterator: `range` is an iterable, so
call `iter` on `range` in order to return an iterator.

Fixes:
```
src/nifreeze/utils.py:56: error:
 Incompatible return value type (got "range", expected "Iterator[int]")  [return-value]
src/nifreeze/utils.py:56: note:
 "range" is missing following "Iterator" protocol member:
src/nifreeze/utils.py:56: note:
     __next__
```

raised for example in:
https://github.com/nipreps/nifreeze/actions/runs/12437972140/job/34728973936#step:8:35