FIX: Provide FD arguments to combined plot function in BOLD notebook
Provide FD arguments to combined plot function in BOLD notebook.

Fixes:
```
File "/home/runner/work/nifreeze/nifreeze/docs/notebooks/bold_realignment.py", line 275, in main
    plot_combined_profile(
TypeError: main.<locals>.plot_combined_profile() missing 2 required positional arguments: 'afni_fd' and 'nifreeze_fd'
```

raised for example in:
https://github.com/nipreps/nifreeze/actions/runs/15007162520/job/42168515561?pr=117#step:14:2223

Take advantage of the commit to rename the function definition variables
so that they do not shadow the outer variables.