STY: Make the motion affines be an array instead of a list
Make the motion affines be an array instead of a list to match the
expected type.

Fixes:
```
test/test_data_dmri.py:89: error:
 Incompatible types in assignment
 (expression has type "list[Any] | None", variable has type "ndarray[Any, Any]")
  [assignment]
```

raised for example at:
https://github.com/nipreps/nifreeze/actions/runs/18449395416/job/52560821339?pr=273#step:8:39