MAINT: Require `nitransforms` 22.x
Require `nitransforms` 22.x.

Fixes:
```
.tox/py310/lib/python3.10/site-packages/nitransforms/io/base.py:4: in <module>
    from scipy.io.matlab.miobase import get_matfile_version
E   ImportError: cannot import name 'get_matfile_version' from 'scipy.io.matlab.miobase'
 (/home/runner/work/nifreeze/nifreeze/.tox/py310/lib/python3.10/site-packages/scipy/io/matlab/miobase.py)
```

raised for example in:
https://github.com/nipreps/nifreeze/actions/runs/14013636690/job/39236852012?pr=83#step:11:58

Importing `scipy.io.matlabt.miobase.get_matfile_version` was removed in:
https://github.com/nipy/nitransforms/pull/151/files

included in release 22.0.0:
https://github.com/nipy/nitransforms/releases/tag/22.0.0