STY: Fix PET classes type checking errors
Fix PET classes type checking errors:
- Ensure that `_locked_fit` is set before attempting to transpose it.
- Ensure that `vol` is not `None` in test before querying about its
  attributes.

Fixes:
```
src/nifreeze/model/pet.py:169: error:
 Item "None" of "Any | None" has no attribute "T"  [union-attr]
```

and
```
test/test_model_pet.py:68: error:
 Item "None" of "ndarray[Any, Any] | None" has no attribute "shape"  [union-attr]
test/test_model_pet.py:69: error:
 Item "None" of "ndarray[Any, Any] | None" has no attribute "dtype"  [union-attr]
```

raised for example at:
https://github.com/nipreps/nifreeze/actions/runs/18428489877/job/52512798218?pr=273#step:8:52