TST: Install `TeX` packages in notebook workflow
Install the necessary `TeX` packages in the test CI so that `LaTeX`
decoration in plots can be employed.

Fixes:
```
FAILED docs/notebooks/data_structures.ipynb::data_structures.ipynb -
 RuntimeError: Failed to process string with tex because latex could not be foun
```

and other related errors.

raised for example in:
https://github.com/jhlegarreta/nifreeze/actions/runs/14813656376/job/41591480555#step:9:844