BUG: Provide missing position arg to local cross validation function
Provide missing position argument to local cross validation function in
GP estimation error analysis script.

Fixes
```
scripts/dwi_gp_estimation_error_analysis.py:210: error:
 Missing positional argument "gpr" in call to "cross_validate"  [call-arg]
scripts/dwi_gp_estimation_error_analysis.py:210: error:
 Unsupported operand types for * ("float" and "dict[int, list[tuple[ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any], ndarray[Any, Any]]]]")  [operator]
scripts/dwi_gp_estimation_error_analysis.py:210: error:
 Argument 4 to "cross_validate" has incompatible type "DiffusionGPR"; expected "int"  [arg-type]
scripts/dwi_gp_estimation_error_analysis.py:211: error:
 "float" has no attribute "tolist"  [attr-defined]
scripts/dwi_gp_estimation_error_analysis.py:212: error:
 Argument 1 to "len" has incompatible type "float"; expected "Sized"  [arg-type]
scripts/dwi_gp_estimation_error_analysis.py:213: error:
 Argument 1 to "len" has incompatible type "float"; expected "Sized"  [arg-type]
scripts/dwi_gp_estimation_error_analysis.py:214: error:
 Argument 1 to "len" has incompatible type "float"; expected "Sized"  [arg-type]
scripts/dwi_gp_estimation_error_analysis.py:215: error:
 Argument 1 to "len" has incompatible type "float"; expected "Sized"  [arg-type]
```

raised for example in:
https://github.com/nipreps/nifreeze/actions/runs/12437972140/job/34728973936#step:8:113