ENH: Remove unused `namedtuple` definition in test
Remove unused `namedtuple` definition in test.

Fixes:
```
test/test_gpr.py:31: error:
 First argument to namedtuple() should be "GradientTablePatch", not "gtab"  [name-match]
```

raised for example in:
https://github.com/nipreps/nifreeze/actions/runs/12437972140/job/34728973936#step:8:129