ENH: Add the dimensionality to the `mask` ndarray parameter annotation
Add the dimensionality to the `mask` ndarray parameter annotation.

Fixes:
```
src/nifreeze/model/_dipy.py:140: error:
 "ndarray" expects 2 type arguments, but 1 given  [type-arg]
```

raised for example in:
https://github.com/nipreps/nifreeze/actions/runs/12437972140/job/34728973936#step:8:103