STYLE: Use the `GradientTable` class for type hinting
Use the `dipy.core.gradientsGradientTable` class for type hinting
instead of `dipy.core.gradients.gradient_table`: the latter is a
function name and hence does not provide type information.

Fixes:
```
src/nifreeze/testing/simulations.py:151: error:
 Function "dipy.core.gradients.gradient_table" is not valid as a type  [valid-type]
src/nifreeze/testing/simulations.py:151: note:
 Perhaps you need "Callable[...]" or a callback protocol?
src/nifreeze/testing/simulations.py:185: error:
 Function "dipy.core.gradients.gradient_table" is not valid as a type  [valid-type]
src/nifreeze/testing/simulations.py:185: note:
 Perhaps you need "Callable[...]" or a callback protocol?
src/nifreeze/testing/simulations.py:207: error:
 gradient_table? has no attribute "b0s_mask"  [attr-defined]
src/nifreeze/testing/simulations.py:208: error:
 gradient_table? has no attribute "bvecs"  [attr-defined]
```