ENH: Provide appropriate type hints to `reg_target_type`
Provide appropriate type hints to the `reg_target_type` parameter of the
`ants._run_registration` function. The expression is set to a tuple in
https://github.com/nipreps/nifreeze/blob/6b6ba707c47b2763c040f3d3a2ceabdcf450eefe/src/nifreeze/estimator.py#L103

Fixes:
```
src/nifreeze/registration/ants.py:459: error:
 Incompatible types in assignment (expression has type "tuple[str, str]", variable has type "str")  [assignment]
```

raised for example in:
https://github.com/nipreps/nifreeze/actions/runs/12437972140/job/34728973936#step:8:133