STY: Fix miscellaneous type checking errors (part 4)
Fix miscellaneous type checking errors:
- Convert the result of the signal permutation back to a list when
  creating multifiber voxel signals. The variable being initialized as
  an empty list forces the type checking to keep the original type.
- Ignore the `np.allclose` argument checking. When `inplace` is `True`
  the resulting value of the function call will be `None`; the type
  checking, being a static check, raises the error, even if it the test
  is protected by a conditional statement. Ignoring the the error is
  safe in this case.
- Ensure that we have at least a 1D arrays for the kdtree query return
  values before indexing them as they may be scalars.
- Ignore calling the trivial model without the required dataset
  argument: the test intends to explicitly check that the parameter is
  needed.
- Ensure that the attributes of the benchmarking class are not `None`
  prior to measuring the fitting time in benchmarking. Attributes are
  initialized to `None`, and even if a proper setup method to assing
  values and instantiate object is called before fitting, `mypy`
  performs an static check and thus believes that they may be `None`
  when querying about their attributes. This patch set ensures that
  attributes are called on proper values.

Fixes:
```
src/nifreeze/testing/simulations.py:410: error:
 Incompatible types in assignment (expression has type "ndarray[Any, Any]",
 variable has type "list[Any]")  [assignment]
```

and
```
test/test_filtering.py:92: error:
 Argument 1 to "allclose" has incompatible type "ndarray[Any, Any] | None";
 expected "Buffer | _SupportsArray[dtype[Any]] | _NestedSequence[_SupportsArray[dtype[Any]]]
 | bool | int | float | complex | str | bytes | _NestedSequence[bool | int | float | complex | str | bytes]"  [arg-type]
test/test_filtering.py:169: error:
 Argument 1 to "allclose" has incompatible type "ndarray[Any, Any] | None";
 expected "Buffer | _SupportsArray[dtype[Any]] | _NestedSequence[_SupportsArray[dtype[Any]]]
 | bool | int | float | complex | str | bytes | _NestedSequence[bool | int | float | complex | str | bytes]"  [arg-type]
test/test_filtering.py:214: error:
 Argument 1 to "allclose" has incompatible type "ndarray[Any, Any] | None";
 expected "Buffer | _SupportsArray[dtype[Any]] | _NestedSequence[_SupportsArray[dtype[Any]]]
 | bool | int | float | complex | str | bytes | _NestedSequence[bool | int | float | complex | str | bytes]"  [arg-type]
```

and
```
src/nifreeze/viz/signals.py:139: error:
 Value of type "signedinteger[Any] | ndarray[tuple[Any, ...], dtype[signedinteger[Any]]]" is not indexable  [index]
src/nifreeze/viz/signals.py:139: error:
 Value of type "float | ndarray[tuple[Any, ...], dtype[floating[_64Bit]]]" is not indexable  [index]
```

and
```
test/test_model.py:69: error:
 Missing positional argument "dataset" in call to "TrivialModel"  [call-arg]
```

and
```
benchmarks/benchmarks/bench_model.py:100: error:
 Item "None" of "Any | None" has no attribute "fit"  [union-attr]
benchmarks/benchmarks/bench_model.py:100: error:
 Item "None" of "Any | None" has no attribute "T"  [union-attr]
benchmarks/benchmarks/bench_model.py:103: error:
 Item "None" of "Any | None" has no attribute "predict"  [union-attr]
```

raised for example in:
https://github.com/nipreps/nifreeze/actions/runs/18446160030/job/52553155548#step:8:40
and
https://github.com/nipreps/nifreeze/actions/runs/18446160030/job/52553155548#step:8:41
and
https://github.com/nipreps/nifreeze/actions/runs/18446160030/job/52553155548#step:8:47
and
https://github.com/nipreps/nifreeze/actions/runs/18446160030/job/52553155548#step:8:52