STY: Fix miscellaneous type errors
Fix miscellaneous type errors:
- Ignore testing the instantiation of the abstract `BaseModel` class and
  pass `None` to silence errors related to its `dataset` positional
  argument.
- Build a proper array for the `DWI` dataset class `dataobj` attribute:
  the previous implementation was passing a tuple with the
  dimensionality instead of an array of actual values.
- Ensure that the result of `fit_predict` is not `None` in test before
  querying about its attributes.
- Annotate base dataset class instances.
- Ignore monkeypatched/dynamically created class when assigning it to
  `nifreeze.model.dmri` module for type checking purposes, as `mypy`,
  being a static checking tool, raises errors for types added at
  runtime.
- Ensure that the argument to `min` is not `None` when deciding the
  number of CPUs: store the CPU count in a variable and use 1 if `None`.

Fixes:
```
test/test_model.py:57: error:
 Cannot instantiate abstract class "BaseModel" with abstract attribute "fit_predict"  [abstract]
```

and
```
test/test_model.py:87: error:
 Argument "dataobj" to "DWI" has incompatible type "tuple[Any, ...]"; expected "ndarray[Any, Any]"  [arg-type]
test/test_model.py:89: error:
 Argument "brainmask" to "DWI" has incompatible type "ndarray[Any, dtype[Any]] | None"; expected "ndarray[Any, Any]"  [arg-type]
```

and
```
test/test_model.py:204: error:
 Item "None" of "ndarray[Any, Any] | None" has no attribute "shape"  [union-attr]
```

and
```
test/test_model.py:209: error:
 Need type annotation for "dataset"  [var-annotated]
test/test_model.py:238: error:
 Need type annotation for "dataset"  [var-annotated]
```

and
```
test/test_model.py:280: error:
 Module has no attribute "AverageDWIModel"  [attr-defined]
```

and
```
test/test_integration.py:47: error:
 Value of type variable "SupportsRichComparisonT" of "min" cannot be "int | None"  [type-var]
```

raised for example in:
https://github.com/nipreps/nifreeze/actions/runs/18429664690/job/52515354565?pr=273#step:8:53