TST: Set new spike expected indices in test after new fixture addition
Set new spike expected indices in test after new fixture addition

Similar to commit 4926a35.

Fixes:
```
  FAILED test/test_analysis.py::test_identify_spikes - assert False
   +  where False = <function array_equal at 0x7ffa597b79b0>(
array([ 42,  48,  61,  80,  98, 103, 113, 143, 324, 387, 422, 436, 449]),
array([ 82,  83, 160, 179, 208, 219, 229, 233, 383, 389, 402, 421, 423,\n       439, 444]))
   +    where <function array_equal at 0x7ffa597b79b0> = np.array_equal
```

raised in:
https://github.com/nipreps/nifreeze/actions/runs/16485937114/job/46610541473?pr=181#step:11:918