STY: Fix `nibabel` image loading type errors
Fix `nibabel` image loading type errors: use the internal `load_api`
function to coerce type checking to consider the loaded image as a
`Nifti1Image` instead of a `FileBasedImage`, which is not guaranteed to
have e.g. th `dataobj` or `affine` attributes.

Fixes:
```
test/test_data_utils.py:56: error: "FileBasedImage" has no attribute "dataobj"  [attr-defined]
```

and similar errors raised for example in:
https://github.com/nipreps/nifreeze/actions/runs/18419804385/job/52491575644?pr=273#step:8:34