ENH: Fix `nibabel` image type checking errors
Fix `nibabel` image type checking errors: add a `load_api` utils
function to provide the appropriate type when loading a `NiBabel`
N-dimensional image.

Solution drawn from:
https://github.com/nipreps/nireports/pull/147/commits/44d0ff6ea79c5ae5aa2ee23406b890c320f84ef0

Fixes:
```
scripts/dwi_gp_estimation_signal_plot.py:113: error:
 "FileBasedImage" has no attribute "get_fdata"  [attr-defined]
scripts/dwi_gp_estimation_signal_plot.py:114: error:
 "FileBasedImage" has no attribute "get_fdata"  [attr-defined]
```

and
```
scripts/optimize_registration.py:173: error:
 Argument 1 to "displacements_within_mask" has incompatible type "FileBasedImage"; expected "SpatialImage"  [arg-type]
```

raised for example in:
https://github.com/nipreps/nifreeze/actions/runs/12437972140/job/34728973936#step:8:63
and
https://github.com/nipreps/nifreeze/actions/runs/12437972140/job/34728973936#step:8:142

Rename the previously existing `utils.py` file to `iterators.py` and
move it to the newly created `utils` module to avoid package name
clashes. Change the related import statements accordingly.