FIX: Use the appropriate `PET` data model frame attribute
Use the appropriate `PET` data model frame attribute when loading data
from a `NIfTI` file: `frame_time` was renamed to `midframe` in commit
62f828e.

Fixes:
```
https://github.com/nipreps/nifreeze/actions/runs/15231996599/job/42840874999?pr=88#step:8:36
```

raised for example at:
src/nifreeze/data/pet.py:275: error: "PET" has no attribute "frame_time"  [attr-defined]
src/nifreeze/data/pet.py:279: error: "PET" has no attribute "frame_time"  [attr-defined]
src/nifreeze/data/pet.py:280: error: "PET" has no attribute "frame_time"  [attr-defined]
src/nifreeze/data/pet.py:290: error: "PET" has no attribute "frame_time"  [attr-defined]